// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// find_word_positions
Rcpp::DataFrame find_word_positions(CharacterVector lines, CharacterVector words);
RcppExport SEXP _spelling_find_word_positions(SEXP linesSEXP, SEXP wordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type lines(linesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type words(wordsSEXP);
    rcpp_result_gen = Rcpp::wrap(find_word_positions(lines, words));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spelling_find_word_positions", (DL_FUNC) &_spelling_find_word_positions, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_spelling(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
