# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_word_positions <- function(lines, words) {
    .Call(`_spelling_find_word_positions`, lines, words)
}

